version: "3.4"

services:
  sql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_USER: kebajikanpelajar@docker.usm.my
      MYSQL_PASSWORD: pelajardatabase
      MYSQL_DATABASE: bhepa_test
      MYSQL_ROOT_PASSWORD: pelajardatabase
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./sql/bhepa_test_update.sql:/docker-entrypoint-initdb.d/bhepa_test_update.sql

  test_db_server:
    build: ./test_db_server
    container_name: test_db_server
    ports:
      - "8092:8000"
    volumes:
      - ./test_db_server:/app
    command: node server.js

  test_db_client:
    build: ./test_db_client
    container_name: test_db_client
    ports:
      - "8090:3000"
    volumes:
      - ./test_db_client:/app
    command: npm start
