version: "3.4"

services:

  mysql8:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_HOST: mysql8
      MYSQL_ROOT_PASSWORD: pelajardatabase
    networks:
      default:
        ipv4_address: 172.17.0.100
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql


  test_db_server:
    build: ./test_db_server
    container_name: test_db_server
    depends_on:
      - sql
    environment:
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./test_db_server:/app
    links:
      - sql
    command: node server.js

  test_db_client:
    build: ./test_db_client
    container_name: test_db_client
    environment:
      NODE_PATH: src
    ports:
      - 8090:3000
    volumes:
      - ./test_db_client/src:/app/src
    links:
      - test_db_server
    command: npm start
