version: '3'

services:
  # Node.js service
  siswa-usm:
    container_name: siswa-usm
    image: siswa-usm  # Replace with the actual image name if it's different
    ports:
      - "8090:3000"  # Map the container's port 3000 to the host's port 8090
    depends_on:
      - mysql8  # This ensures that the "mysql8" service is started before "siswa-usm"

  # MySQL service
  mysql8:
    container_name: mysql8
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pelajardatabase
      MYSQL_DATABASE: mysql8
      MYSQL_USER: kebajikanpelajar@docker.usm.my
      # MYSQL_PASSWORD: your_mysql_password
    ports:
      - "3306:3306"
