version: '3'

services:
  # Node.js backend and React frontend service
  siswa-usm:
    container_name: siswa-usm
    image: siswa-usm
    ports:
      - "8090:3000"  # Expose React frontend on host port 8090
      - "8092:3001"  # Expose Node.js backend on host port 8092

  # MySQL service
  mysql8:
    container_name: mysql8
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pelajardatabase
      MYSQL_DATABASE: mysql8
      # MYSQL_USER: kebajikanpelajar@docker.usm.my
      # MYSQL_PASSWORD: your_mysql_password
    ports: