version: "3.4"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pelajardatabase
      MYSQL_DATABASE: bhepa_test
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  test_db_server:
    build: ./test_db_server
    container_name: test_db_server
    depends_on:
      - mysql
    environment:
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
    expose:
      - "8000"
    links:
      - mysql
    volumes:
      - ./test_db_server:/app
    command: node server.js

  test_db_client:
    build: ./test_db_client
    container_name: test_db_client
    environment:
      NODE_PATH: src
    ports:
      - 8090:3000
    volumes:
      - ./test_db_client/src:/app/src
    depends_on:
      - test_db_server
    command: npm start
