version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app
    container_name: react-app
    ports:
      - "80:8090"
    volumes:
      - ./siswa-usm/test_db_client:/app
    working_dir: /app
    command: npm start
